game:main.o background.o hero.o
	gcc main.o background.o hero.o -o game -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer -lm
main.o:main.c
	gcc -c main.c
background.o:background.c
	gcc -c background.c
hero.o:hero.c
	gcc -c hero.c