game:main.o hero.o colision.o entite_secondaire.o background.o enigme.o enigme_fonctions.o settings.o menu.o
	gcc menu.o main.o hero.o colision.o entite_secondaire.o background.o enigme.o enigme_fonctions.o settings.o -o game -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf 
main.o:main.c
	gcc -c main.c
hero.o:hero.c
	gcc -c hero.c
background.o:background.c
	gcc -c background.c
entite_secondaire.o:entite_secondaire.c
	gcc -c entite_secondaire.c
colision.o:colision.c
	gcc -c colision.c
enigme_fonctions.o:enigme_fonctions.c
	gcc -c enigme_fonctions.c 
enigme.o:enigme.c
	gcc -c enigme.c 
settings.o:settings.c
	gcc -c settings.c
menu.o:menu.c
	gcc -c menu.c