game:jeu.o hero.o colision.o entite_secondaire.o background.o enigme.o enigme_fonctions.o menuP.o settings.o
	gcc jeu.o hero.o colision.o entite_secondaire.o background.o enigme.o enigme_fonctions.o menuP.o settings.o -o game -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -ggdb
jeu.o:jeu.c
	gcc -c jeu.c
hero.o:hero.c
	gcc -c hero.c
background.o:background.c
	gcc -c background.c
entite_secondaire.o:entite_secondaire.c
	gcc -c entite_secondaire.c
colision.o:colision.c
	gcc -c colision.c
enigme_fonctions.o:enigme_fonctions.c
	gcc -c enigme_fonctions.c 
enigme.o:enigme.c
	gcc -c enigme.c 
menuP.o:menuP.c
	gcc -c menuP.c
settings.o:settings.c
	gcc -c settings.c