game:main.o jeu.o hero.o collision.o entite_secondaire.o background.o enigme.o enigme_fonctions.o menu.o   
	gcc main.o jeu.o hero.o collision.o entite_secondaire.o background.o enigme.o enigme_fonctions.o menu.o  -o game -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -ggdb
jeu.o:jeu.c
	gcc -c jeu.c -ggdb
hero.o:hero.c
	gcc -c hero.c -ggdb
background.o:background.c
	gcc -c background.c -ggdb
entite_secondaire.o:entite_secondaire.c
	gcc -c entite_secondaire.c -ggdb
collision.o:collision.c
	gcc -c collision.c -ggdb
enigme_fonctions.o:enigme_fonctions.c
	gcc -c enigme_fonctions.c -ggdb 
enigme.o:enigme.c
	gcc -c enigme.c -ggdb
menu.o:menu.c
	gcc -c menu.c -ggdb
main.o:main.c
	gcc -c main.c -ggdb
