game:main.o jeu.o hero.o collision.o entite_secondaire.o background.o enigme.o enigme_fonctions.o menu.o   
	gcc main.o jeu.o hero.o collision.o entite_secondaire.o background.o enigme.o enigme_fonctions.o menu.o  -o game -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -ggdb
jeu.o:jeu.c
	gcc -c jeu.c
hero.o:hero.c
	gcc -c hero.c
background.o:background.c
	gcc -c background.c
entite_secondaire.o:entite_secondaire.c
	gcc -c entite_secondaire.c
collision.o:collision.c
	gcc -c collision.c
enigme_fonctions.o:enigme_fonctions.c
	gcc -c enigme_fonctions.c 
enigme.o:enigme.c
	gcc -c enigme.c 
menu.o:menu.c
	gcc -c menu.c
main.o:main.c
	gcc -c main.c
